In [55]:
import numpy as np
from random import random as rd

In [33]:
fname = 'example.in'

In [40]:
ans = list(open(fname).read().splitlines())

In [41]:
R,C,L,H = map(int, ans[0].split())
data = ans[1:]

Initialize an ndarray reprresenting the pizza where each cell is going to be 0,1 representing the two topings. 

We set `tomato=0, mushroom=1`.

In [42]:
pizza = np.ones((R, C), dtype=int)

for i in range(R):
    for j in range(C):
        if data[i][j] == 'M':
            pizza[i,j] = -1

In [43]:
print pizza

[[ 1  1  1  1  1]
 [ 1 -1 -1 -1  1]
 [ 1  1  1  1  1]]


----

## Evolution

In [74]:
N = 10
population = N**2
generation = 10
p_kill = 0.0001

In [46]:
def get_size(arr):
    return np.count_nonzero(arr[arr == 0])

In [ ]:
def fit(....):
    
    
    
    
    return

In [ ]:
def random_instance():
    slices = []
    
    
    
    return get_size(arr)

In [21]:
def is_legal(arr, l, h):
    """
    Given array and L,H determine if the slice is legal: if there are at least L tomatoes and L mushrooms
    and if size of slice is less than H.
    """
    size = arr.size
    if size > h:     # optional, we may drop this
        return False
    total = arr.sum()
    return ((size - 2*l) >= 0) and (size - 2*l) >= abs(total) 

In [22]:
def get_posibble_slices(R,C,x,y,H):
    ans = []
    for X in range(max(0,x-H),min(R,x+H)):
        for Y in range(max(0,y-H),min(C,y+H)):
            if abs((X-x+1)*(Y-y+1)) <= H:
                ans.append([X,Y])
    return np.array(ans, dtype=int)

In [222]:
def get_4_coord(i1,i2):
    i11,i12 = i1
    i21,i22 = i2
    return [i1,i2,[i21,i12],[i11,i22]]

In [29]:
def get_2_coord(i1,i2):
    """Given 2 coordinates, return 2 coordinates such that the first it top left and second is bottom right"""
    i11,i12 = i1
    i21,i22 = i2
    return [[min(i11,i21),min(i12,i22)],[max(i11,i21),max(i12,i22)]]

In [23]:
def is_collision(i1,i2,j1,j2):
    X = max(0, min(i1[0],i2[0])-max(j1[0],j2[0]))
    Y = max(0, min(i1[1],i2[1])-max(j2[1],j2[1]))
    print X,Y
    return X*Y > 0