In [140]:
import numpy as np
from random import random as rd
from random import randint as ri
from random import shuffle

In [33]:
fname = 'example.in'

In [40]:
ans = list(open(fname).read().splitlines())

In [41]:
R,C,L,H = map(int, ans[0].split())
data = ans[1:]

Initialize an ndarray reprresenting the pizza where each cell is going to be 0,1 representing the two topings. 

We set `tomato=0, mushroom=1`.

In [42]:
pizza = np.ones((R, C), dtype=int)

for i in range(R):
    for j in range(C):
        if data[i][j] == 'M':
            pizza[i,j] = -1

In [43]:
print pizza

[[ 1  1  1  1  1]
 [ 1 -1 -1 -1  1]
 [ 1  1  1  1  1]]


----

## Evolution

There are 4 function:
1. Fit - which calculated its area.
2. Random_instance - creates a valid pizza slice list
3. Mate - takes two slice list and create a hybrid slices
4. Mutate - with random probability drops and creates new slices

In [153]:
N = 10
population = N**2
generation = 10
num_mutate = 200
p_kill = 0.0001

In [46]:
def get_size(arr):
    return np.count_nonzero(arr[arr == 0])

In [76]:
def fit(slices):
    return sum(map(lambda s: (abs(s[1][1] - s[0][1]) + 1) * (abs(s[1][0] - s[0][0]) + 1), slices))

In [157]:
def is_valid(matrix, slices, L, H):
    dirty = np.ones(matrix.shape)
    for s in slices:
        r1, c1 = s[0]
        r2, c2 = s[1]
        if abs(r2 - r1) * abs(c2 - c1) > H:
            return False
        if np.sum(dirty[r1:(r2 + 1), c1:(c2 + 1)]) < L:
            return False
        if not np.any(dirty[r1:(r2 + 1), c1:(c2 + 1)]):
            return False
        dirty[r1:(r2 + 1), c1:(c2 + 1)] = 0
    return True

In [158]:
def mutate(slices):
    mutated = False
    new_slices = slices
    for a in range(num_mutate):
        up_down = 1 if rd() > 0.5 else -1
        r1 = ri(0, len(slices))
        r2 = ri(0,1)
        r3 = ri(0,1)
        new_slices[r1,r2,r3] = new_slices[r1,r2,r3] + up_down
        if is_valid(new_slices):
            return new_slices

In [173]:
def mate(sol1, sol2):
    all_sol = sol1 + sol2
    shuffle(all_sol)
    ans = []
    for s in all_sol:
        if is_valid(ans + [s]):
            ans += [s]
    return ans